# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45c9975e1c4d6176dadad7c1bde16a157ecca552d4e26ea9943473f6d3700ae335149c515aa81b7bacf4033c796e67a75adb274f900fb55ceacd51260122db73

test:
  secret_key_base: 6a598f3e28300c145faf1754932b29e17bf3666b3395be023c509f9d1ee9e6d612cb0abe9150e54fe922495b68206a53720bcdc39f49906663ff0ace9d0c7ce4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
